version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3001:80
    environment: 
      - PMA_HOST=db
    depends_on:
      - db
      - web

  web:
    build: .
    ports:
      - 3000:80
    volumes:
      - ./public_html:/var/www/html/
    depends_on:
      - db
